# Generated by Django 5.0.4 on 2024-04-25 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_projeto", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="itens",
            name="deleted_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="listas",
            name="deleted_at",
            field=models.DateTimeField(null=True),
        ),
    ]
