# Generated by Django 5.0.4 on 2024-05-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_projeto", "0002_itens_deleted_at_listas_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="itens",
            name="status",
            field=models.BooleanField(default=0),
        ),
    ]
