# Generated by Django 5.0.4 on 2024-05-31 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_projeto", "0004_remove_itens_status_postagens"),
    ]

    operations = [
        migrations.AddField(
            model_name="itens",
            name="is_done",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="Postagens",
        ),
    ]
