[default]
DATABASE_ENGINE = "django.db.backends.mysql"
DATABASE_NAME = "django_web"
DATABASE_USER = ""
DATABASE_PASSWORD = ""
DATABASE_HOST = "localhost"
DATABASE_PORT = "3306"
SECRET_KEY = ""

[development]
DEBUG = true

[production]
DEBUG = false